### ISSUE TITLE
Season Two

### ISSUE THREAD

**Issue by JDot-Cv** [InternationalGangsters/issues#27]
Things that need to be worked on: 

- [x] - Layout Changes
- [x] - Cars rework (to add seasonal cars)
- [x] - Seasonal features to be decided
- [x] - Backdate payouts upon purchasing VIP

**Comment by dantennyson** [comment]
[OPERATION KILL TS - SEASONS.docx](https://github.com/InternationalGangsters/issues/files/10380895/OPERATION.KILL.TS.-.SEASONS.docx)
