### ISSUE TITLE
Fixing the profit blocking buttons

### ISSUE THREAD

**Issue by WilliamWinterDev** [InternationalGangsters/issues#48]
**Describe the bug**
When you have a casino its like the profit box is blocking that whole row from being used even though the box only takes up a tiny portion of the page.

**Expected behavior**
Only the profit box will actually block clicking / would link to my props

**Screenshots**
See telegram, is a private video screenshot of it happening

**Additional context**
This seems to be mobile only due to the profit only showing there

**Comment by JDot-Cv** [comment]
Changed to have profit on player stats
